
 export const projectsData = [
    {
      id: 1,
      title: "Image Gallery",
      description: "React Draggable Image gallery to sort images",
      image: "/images/projects/interview_image_gallery.gif",
      tag: ["All", "Interview"],
      gitUrl: "https://github.com/dhirajtek13/Image-gallery-reorder",
      previewUrl: "https://image-gallery-reorder.vercel.app/",
    },
    {
      id: 2,
      title: "HTML Portfolio",
      description: "Portfolio made with Udemy classes",
      image: "/images/projects/html_portfolio_v1.gif",
      tag: ["All", "Personal"],
      gitUrl: "https://github.com/dhirajtek13/personal_website",
      previewUrl: "https://dhirajtek13.github.io/personal_website/",
    },
    {
      id: 3,
      title: "Project Management v1",
      description: "Project management to add project done using udemy course.",
      image: "/images/projects/ReactProjectManager.gif",
      tag: ["All", "Personal"],
      gitUrl: "https://github.com/dhirajtek13/project_management_app_v1",
      previewUrl: "https://project-management-app-v1.vercel.app/",
    },
    {
      id: 4,
      title: "All year calendar",
      description: "All year calendar",
      image: "/images/projects/singleCalendar.gif",
      tag: ["All", "Interview"],
      gitUrl: "https://github.com/dhirajtek13/calendarapp",
      previewUrl: "https://calendarapp-dhirajtek13.vercel.app/",
    },
    {
      id: 5,
      title: "Blog website",
      description: "Blog HTML JavaScript website",
      image: "/images/projects/blogJavascript.gif",
      tag: ["All", "Interview"],
      gitUrl: "https://github.com/dhirajtek13/blog",
      previewUrl: "https://blog-l5kz.onrender.com/",
    },
    {
      id: 6,
      title: "Customize Print",
      description: "Threejs and animation in react",
      image: "/images/projects/customizedPrint.gif",
      tag: ["All", "Personal"],
      gitUrl: "https://github.com/dhirajtek13/threejs_ai",
      previewUrl: "https://threejs.hindileads.com/",
    },
    {
        id: 7,
        title: "Redux Store",
        description: "Very basic example of react-redux",
        image: "/images/projects/reduxExample.png",
        tag: ["All", "Interview"],
        gitUrl: "https://github.com/dhirajtek13/redux-tut",
        previewUrl: "https://redux-tut-dhirajtek13.vercel.app/",
      },
      {
        id: 8,
        title: "Cloakroom Display",
        description: "Cloakroom checkout system to display token number in particular color sequence",
        image: "/images/projects/cloakroomCheckout.gif",
        tag: ["All", "Interview"],
        gitUrl: "https://github.com/dhirajtek13/CRDisplayNode",
        previewUrl: "https://cr-display-node.vercel.app/",
      },
      {
        id: 9,
        title: "Cloakroom Display",
        description: "Cloakroom checkout system to display token number in particular color sequence",
        image: "/images/projects/cloakroomCheckout.gif",
        tag: ["All", "Interview"],
        gitUrl: "https://github.com/dhirajtek13/CRDisplayNode",
        previewUrl: "https://cr-display-node.vercel.app/",
      },
      {
        id: 10,
        title: "Todo List",
        description: "Todo list with given css",
        image: "/images/projects/todolist.png",
        tag: ["All", "Interview"],
        gitUrl: "https://github.com/dhirajtek13/todolist",
        previewUrl: "https://todolist-035j.onrender.com/",
      },
      {
        id: 11,
        title: "Amazing Lash Studio",
        description: "Eyelash shopping app",
        image: "/images/projects/amazinglash.png",
        tag: ["All", "Company"],
        gitUrl: "/",
        previewUrl: "https://www.amazinglashstudio.com/",
      },
      {
        id: 12,
        title: "Full Psycle",
        description: "Cycle service booking and managament app",
        image: "/images/projects/fullpsycle.png",
        tag: ["All", "Company"],
        gitUrl: "/",
        previewUrl: "https://www.fullpsycle.com/",
      },
      {
        id: 13,
        title: "Fruzzi",
        description: "Juice restaurant app",
        image: "/images/projects/fruzzi.png",
        tag: ["All", "Company"],
        gitUrl: "/",
        previewUrl: "https://fruzzi-website.nebhub4.com/",
      },
      {
        id: 14,
        title: "Mobilefold",
        description: "Mart equipment solutions",
        image: "/images/projects/mobilefold.png",
        tag: ["All", "Company"],
        gitUrl: "/",
        previewUrl: "https://www.customerminded.com/",
      },
      {
        id: 15,
        title: "Collateral360",
        description: "Real estate related bank loan and other form",
        image: "/images/projects/collateral360.png",
        tag: ["All", "Company"],
        gitUrl: "/",
        previewUrl: "https://www.collateral360.com/",
      },
      {
        id: 16,
        title: "Pinlocal",
        description: "One point contact and search solutions for various services",
        image: "/images/projects/pinlocal.png",
        tag: ["All", "Company"],
        gitUrl: "/",
        previewUrl: "https://www.pinlocal.com/",
      },
      {
        id: 17,
        title: "Social Suite",
        description: "Web crawler for various social media apps",
        image: "/images/projects/socialsuite.png",
        tag: ["All", "Company"],
        gitUrl: "/",
        previewUrl: "https://socialpromo.biz/",
      },
      {
        id: 18,
        title: "Cybx website",
        description: "Company website",
        image: "/images/projects/cybx.png",
        tag: ["All", "Company"],
        gitUrl: "/",
        previewUrl: "https://cybxtechnolabs.com/",
      },
      {
        id: 19,
        title: "Hutch waldo",
        description: "Hutch waldo restaurant franchise",
        image: "/images/projects/hutchwaldo.png",
        tag: ["All", "Company"],
        gitUrl: "/",
        previewUrl: "https://hutchandwaldo.com/",
      },
      {
        id: 20,
        title: "EMA Aesthetics",
        description: "Treatment center service",
        image: "/images/projects/ema.png",
        tag: ["All", "Company"],
        gitUrl: "/",
        previewUrl: "https://emathesource.com/",
      },
  ];
  