
 export const projectsData = [
    {
      id: 1,
      title: "Image Gallery",
      description: "React Draggable Image gallery to sort images",
      image: "/images/projects/interview_image_gallery.gif",
      tag: ["All", "Interview"],
      gitUrl: "https://github.com/dhirajtek13/Image-gallery-reorder",
      previewUrl: "https://image-gallery-reorder.vercel.app/",
    },
    {
      id: 2,
      title: "HTML Portfolio",
      description: "Portfolio made with Udemy classes",
      image: "/images/projects/html_portfolio_v1.gif",
      tag: ["All", "Personal"],
      gitUrl: "https://github.com/dhirajtek13/personal_website",
      previewUrl: "https://dhirajtek13.github.io/personal_website/",
    },
    {
      id: 3,
      title: "Project Management v1",
      description: "Project management to add project done using udemy course.",
      image: "/images/projects/ReactProjectManager.gif",
      tag: ["All", "Personal"],
      gitUrl: "https://github.com/dhirajtek13/project_management_app_v1",
      previewUrl: "https://project-management-app-v1.vercel.app/",
    },
    {
      id: 4,
      title: "All year calendar",
      description: "All year calendar",
      image: "/images/projects/singleCalendar.gif",
      tag: ["All", "Interview"],
      gitUrl: "https://github.com/dhirajtek13/calendarapp",
      previewUrl: "https://calendarapp-dhirajtek13.vercel.app/",
    },
    {
      id: 5,
      title: "Blog website",
      description: "Blog HTML JavaScript website",
      image: "/images/projects/blogJavascript.gif",
      tag: ["All", "Interview"],
      gitUrl: "https://github.com/dhirajtek13/blog",
      previewUrl: "https://blog-l5kz.onrender.com/",
    },
    {
      id: 6,
      title: "Customize Print",
      description: "Threejs and animation in react",
      image: "/images/projects/customizedPrint.gif",
      tag: ["All", "Personal"],
      gitUrl: "https://github.com/dhirajtek13/threejs_ai",
      previewUrl: "https://threejs.hindileads.com/",
    },
    {
        id: 7,
        title: "Redux Store",
        description: "Very basic example of react-redux",
        image: "/images/projects/reduxExample.png",
        tag: ["All", "Interview"],
        gitUrl: "https://github.com/dhirajtek13/redux-tut",
        previewUrl: "https://redux-tut-dhirajtek13.vercel.app/",
      },
  ];
  